# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 89637a2871f02b4c82a01e626c850c6fe1572ebd0c5703a084aa3c151ec63dc5d8c82bb7068020ae48db65eca08931f893d93513337a4c57a72193b584e6a0c3

test:
  secret_key_base: 5333a8d328e2471ad145e9e9376404602952e34cb1cd4070ad1b27ee336aa950aa794d39477a344c7542a0d0f315cc07abb11877fa40eb8159fa3f562df3eecd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
